{
 "title": "AMD-GPU Dashboard",
 "description": "Dashboard to visualize AMD GPU metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "hostname", "label": "Node", "query": { "query": "label_values(hostname)" } }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "GPU Mem Utilization",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radeon_exporter_mem_info_vram_used{hostname=\"$hostname\"}",
     "legendFormat": "{{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radeon_exporter_gpu_busy_percent{hostname=\"$hostname\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Memory Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radeon_exporter_mem_busy_percent{hostname=\"$hostname\"}",
     "legendFormat": "GPU Memory {{gpu_id}}"
    },
    {
     "expr": "radeon_exporter_mem_info_vram_used{hostname=\"$hostname\"} / radeon_exporter_mem_info_vram_total{hostname=\"$hostname\"}",
     "legendFormat": "VRAM {{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Health",
   "type": "stat",
   "description": "Health of the GPU (0 = Unhealthy | 1 = Healthy)",
   "gridPos": { "h": 13, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radeon_exporter_temp1_input{hostname=\"$hostname\"} / 1000 < 85",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Utilization (%)",
   "type": "timeseries",
   "description": "Graphics engine usage in Percentage (0-100)",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "radeon_exporter_gpu_busy_percent{hostname=\"$hostname\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage (W)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "radeon_exporter_power1_input{hostname=\"$hostname\"} / 1000000",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Temperature (Celsius)",
   "type": "timeseries",
   "description": "Current junction/hotspot temperature in Celsius",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "radeon_exporter_temp1_input{hostname=\"$hostname\"} / 1000",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Mem Utilization (GB)",
   "type": "bargauge",
   "description": "Used VRAM memory of the GPU (in MB)",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radeon_exporter_mem_info_vram_used{hostname=\"$hostname\"} / 1000000000",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Average GPU Utilization (All GPUs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(radeon_exporter_gpu_busy_percent{hostname=\"$hostname\"}[10m]))",
     "legendFormat": "Average GPU Utilization"
    }
   ]
  },
  {
   "title": "Avg GPU & Mem Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(radeon_exporter_gpu_busy_percent{hostname=\"$hostname\"})",
     "legendFormat": "Avg. GPU Utilization"
    },
    {
     "expr": "avg((radeon_exporter_mem_info_vram_used) / (radeon_exporter_mem_info_vram_total)) * 100",
     "legendFormat": "Avg. Memory Utilization"
    },
    {
     "expr": "radeon_exporter_mem_busy_percent{hostname=\"$hostname\"}",
     "legendFormat": "Avg. GPU Memory Utilization"
    }
   ]
  },
  {
   "title": "GPU Utilization Avg/Max/Min (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(radeon_exporter_gpu_busy_percent{hostname=\"$hostname\"})",
     "legendFormat": "Avg. GPU Utilization (%)"
    },
    {
     "expr": "min(radeon_exporter_gpu_busy_percent{hostname=\"$hostname\"})",
     "legendFormat": "Min. GPU Utilization (%)"
    },
    {
     "expr": "max(radeon_exporter_gpu_busy_percent{hostname=\"$hostname\"})",
     "legendFormat": "Max. GPU Utilization (%)"
    }
   ]
  }
 ]
}